"""Add region and manager_id to User model

Revision ID: 5130ea57b3c2
Revises: 
Create Date: 2025-04-15 11:47:51.274200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5130ea57b3c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mbo', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('optional_link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'users', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.drop_column('manager_id')
        batch_op.drop_column('region')

    with op.batch_alter_table('mbo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('optional_link',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
